<?php

namespace Apps\Html\Controllers;

use Common\WxPay\CLogFileHandler;
use Common\WxPay\JsApiPay;
use Common\WxPay\Log;
use Common\WxPay\WxPayApi;
use Common\WxPay\WxPayUnifiedOrder;
use Config\WxPayConfig;
use Apps\Models\ExpertModel;

class OrderController extends CommonController
{
    protected $tools;

    public function start()
    {
        //初始化日志
        $logHandler = new CLogFileHandler(WXPAY_LOG_DIR . DIRECTORY_SEPARATOR . date('Y-m-d') . '.log');
        $log = Log::Init($logHandler, 15);
        Log::DEBUG("begin notify: order");
        echo $this->output();
    }

    protected function getData()
    {
        // TODO: Change the autogenerated stub
        $data = array_merge($this->getCustomData(), $this->getCommonData());
        $data['shareData'] = json_decode($data['shareData'], true);
        $data['shareData']['title'] = str_replace('doctor', $data['name'], $data['shareData']['title']);
        $data['shareData'] = json_encode($data['shareData']);
        return $data;
    }

    protected function getCustomData()
    {
        $openid = $this->getOpenId();
        return $this->getJsApiParameter($openid, $this->getUserId($openid));
    }

    protected function getShareLink()
    {
        return WxPayConfig::ORDER_SHARE_URL; // TODO: Change the autogenerated stub
    }

    protected function getOpenId()
    {
        $this->tools = new JsApiPay();
        $openId = $this->tools->GetOpenid();
        return $openId;
    }

    protected function getUserId($openid)
    {
        $user_info = $this->user->get(array('openid' => $openid));
        if (empty($user_info['subscribe'])) {
            header("Location: " . WxPayConfig::SUBSCRIBE_URL); //提示用户关注微信号链接
        }
        return $user_info['userid'];
    }

    protected function getJsApiParameter($openid, $userid)
    {
        $expert = new ExpertModel();
        $expert_info = $expert->get(array('id' => $_GET['expert']));
        $expert_info = $expert_info[0];
        $input = new WxPayUnifiedOrder();
        $input->SetBody("MomChat专家咨询服务"); //商品名称
        $input->SetAttach("MomChat");
        $input->SetOut_trade_no(WxPayConfig::MCHID . date("YmdHis"));
        $input->SetTotal_fee($expert_info['price']); //商品费用
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("专家咨询");
        $input->SetNotify_url(WxPayConfig::NOTIFY_URL);//回调网页
        $input->SetTrade_type("JSAPI");//支付方式
        $input->SetOpenid($openid);
        $order = WxPayApi::unifiedOrder($input);
        $jsApiParameters = $this->tools->GetJsApiParameters($order);
        $data = array(
            'jsApiParameters' => $jsApiParameters,
            //'success_url' => WxPayConfig::SUCCESS_CALL_BACK_URL,
            'failure_url' => WxPayConfig::FAILURE_CALL_BACK_URL,
            'price' => '￥' . sprintf('%.2f', $expert_info['price'] / 100),
            'name' => $expert_info['name'],
            'jobtitle' => $expert_info['title'],
            'service' => $expert_info['service'],
            'service_time' => $expert_info['time'] / 60 . '分钟',
            'order' => array('client' => $userid, 'expert' => $expert_info['id'], 'time' => $expert_info['time'])
        );
        return $data;
    }
}